### PR TITLE
Support the new MonadFail class introduced by ghc-8.8.1.

### LINKED ISSUE #16: bencode-0.6.0.0: build failure with ghc 8.8.1
bencode-0.6.0.0 ships a broken `Setup.hs` file:

~~~
Setup.lhs:5:31: error:
    Variable not in scope: defaultUserHooks :: UserHooks
  |
5 | > main = defaultMainWithHooks defaultUserHooks
  |                               ^^^^^^^^^^^^^^^^
~~~

You can simply delete that file from the release tarball since your package is of `BuildType: Simple` anyway.

### PR DESCRIPTION
**Pull request by peti**
See https://prime.haskell.org/wiki/Libraries/Proposals/MonadFail for details.

Fixes https://github.com/creichert/bencode/issues/16.

### CODE REVIEW

**Comment by peti** [comment]
Note that the failures on Travis-CI are unrelated to these changes. The failures stem from the fact that the quickcheck test suite fails, presumably because of an error in the test or in the library.

**Comment by creichert** [comment]
@peti I updated and merged my PR for CI to get things moving. Do you think #13 provides more compatibility with older GHC versions? It might help if you update/rebase your PR so we can look at the latest builds.

Thanks for your patience, I can merge a MonadFail fix today if I can get a PR that passes the new ci scripts which are g2g.

**Comment by peti** [comment]
> Do you think #13 provides more compatibility with older GHC versions?

No, that is the exact same fix I used. Makes no difference in terms of compatibility.

**Comment by peti** [comment]
Will you release a new version so that this fix actually reaches users of the package?

**Pull request merged**
