### PR TITLE
BReader reader monad

### LINKED ISSUE #7: Are the combinators in Data.BEncode.Parser actually parsers?
I'm inclined to say that the data one accesses through these "parsers" is already parsed by the combinators in Data.BEncode. The name "parser" at this point seems like a holdover. Can we think of a more appropriate name? Accessors? Getters?

Is it worth renaming things? Or should there just be an explanatory note?

### PR DESCRIPTION
**Pull request by matthewleon**
Restores the old `BParser` with a note indicating it will be deprecated and introduces the new `BReader` module. This new module derives all its typeclass implementations from `mtl` and exposes a simple, minimal API. It is fully documented with included `docstring` style tests.

Resolves #7.

### CODE REVIEW

**Comment by matthewleon** [comment]
I see this is failing in Travis, which seems to be pulling in more recent versions of `mtl` than `stack` is giving me on my machine. Should we settle on which version to use in our dependencies? I'll check what Parsec likes.

**Comment by matthewleon** [comment]
Hmm, odd. Seems like the failures are only on old versions of GHC. Any insight?

**Comment by matthewleon** [comment]
Hmm, looks like the issue has nothing to do with deprecated monad transformers but rather with an old version of `docstring`. Will look into what can be done.

**Comment by creichert** [comment]
Cool! I'm not sure about the build error yet but I'll be able to pull a
little later and help.

A few questions:
- Why use the deprecated ErrorT over ExceptT? I don't think there is a
  large difference between the two in the new module anyways.
- I'm a little fuzzy on the Reader terminology.  I think the reason they
  are called parsers is because that is generally what the user of the
  library will be focused on doing with some raw data.

Most popular parsing libs (like aeson) have a similar interface called
Parser. If the user imports BReader, it might not be immediately clear
that they are, in fact, getting the parsing functionality too.

Regardless of the naming, this patch has major benefits overall.
Deriving the mtl classes and the cleaner parsers are a major plus.

One other benefit here is that we won't have to worry about breaking any
old code and can properly deprecate the older modules. I think the
module hierarchy is backward but let's leave it be.

**Comment by matthewleon** [comment]
> - Why use the deprecated ErrorT over ExceptT? I don't think there is a
>   large difference between the two in the new module anyways.

Because I was using LTS haskell while coding and it didn't have `ExceptT`, which is only in the latest release of `mtl`. Using `ExceptT` is the right approach, though, so I'll just switch to Stackage nightlies and get the latest `mtl`.

> - I'm a little fuzzy on the Reader terminology.  I think the reason they
>   are called parsers is because that is generally what the user of the
>   library will be focused on doing with some raw data.

You're probably right. Let me think about it and propose an appropriate naming strategy. Not exactly sure what to do given that the old module sits at `.Parser`. Perhaps use `.BParser`?

> One other benefit here is that we won't have to worry about breaking any
> old code and can properly deprecate the older modules. I think the
> module hierarchy is backward but let's leave it be.

Possible trick: have the root module re-export my redefined parser-combinators? There might be a name clash.

Still a fair bit to think through before releasing a next version.

**Comment by creichert** [comment]
> Possible trick: have the root module re-export my redefined parser-combinators? There might be a name clash.

Some variant of this is the best course, in my opinion. We could leave the old one exposed and hide the new implementations under Data.Bencode. It's a little tricky since it wasn't done this way originally but it might be possible.

**Comment by matthewleon** [comment]
Okay. I'll try some new approaches in my repo and open PRs when they seem like a potential good fit. Close this for now?

**Comment by creichert** [comment]
Well, I was still hoping to merge this code after a few fixes but if you think it's best to resubmit I am fine with that.

**Comment by creichert** [comment]
To be clear, 99% of the problems stem from not wanting to break any old code. The implementation itself is very good.

**Comment by matthewleon** [comment]
Oh I agree, just not sure what proper practice is. I don’t really want this merged until I address the problems it creates in my repo. I don’t know if the right approach is “keep the old PR open and fix things on it” or “open a new PR”, seems like different projects deal with this differently. Your call.

**Comment by matthewleon** [comment]
Okay, more notes on `ErrorT` vs. `ExceptT`.

Sadly, for the moment it looks like GHC 7.8 ships with `transformers` at `0.3.0.0`, which doesn't do `Except`. The only version of `mtl` that has `ExceptT` is the latest, `2.2.1`, which in turn requires `transformers == 0.4.*`. Bit of cabal hell for you, I'm afraid: https://travis-ci.org/matthewleon/bencode/jobs/72619087
Option 1: swallow our pride, stick with the deprecated `ErrorT`, and accept that there will be a deprecation warning on GHC 7.10.
Option 2: stick a maximum bound on our dependency at `mtl <= 2.2.0`. We'd have to cap our dependency at `2.3.0` with the option 1, anyway, as that version might lose `ErrorT`. So this might not be so bad.

Option 3: CPP.

Thoughts?

**Comment by creichert** [comment]
I'm confused by the build error. Can you try:

```
transformers >=0.4.2
mtl >=2.2.1
```

in the library (and possibly the test-suite) without the impl check?

I've briefly started working on a solution to the module layout issue
but I need to test it against a few other packages, first.

**Comment by matthewleon** [comment]
Sadly that won't do. Here's a description of the problem: https://www.fpcomplete.com/blog/2014/05/lenient-lower-bounds

Looks like there is a potential solution here: https://hackage.haskell.org/package/transformers-compat

Gonna try it.

**Comment by matthewleon** [comment]
Latest commit on my reader branch fixes all deprecation warnings and gets the OK from Travis: https://github.com/matthewleon/bencode/tree/reader

Gonna push this to my master.

**Comment by matthewleon** [comment]
Master is updated and ready for a pull. Let me know if you have further concerns.

**Comment by creichert** [comment]
Well done, thanks! There are only a few things left I want to do before a major version release on Hackage. Mainly, I'm interested in re-exporting the new functionality through Data.BEncode but allowing users to access Data.BEncode.Parser directly with the warning. I've also been pondering a set of classes (ToBEncode/FromBEncode) similar to aeson's ToJSON/FromJSON.

**Comment by matthewleon** [comment]
Interesting idea... Would you want to go all the way and support generics,
too?

**Comment by creichert** [comment]
Yea, I think that would be a great addition.

**Comment by matthewleon** [comment]
Generics are probably not worth it on reflection given how little real-world data actually is bencoded. At least not for a next version...

**Comment by creichert** [comment]
You are probably right. I think it's a cool idea but might be worth
putting off for now. This does remind me to schedule a release for later
this week, though.

**Pull request merged**
