### PR TITLE
Fix list and clean up other BParser implementations

### PR DESCRIPTION
**Pull request by matthewleon**
Ensure a list BParser fails the first time its sub-parser fails.

Clean up other BParser functions.

Add appropriate tests.

### CODE REVIEW

**Comment by creichert** [comment]
I guess the show instance for `ByteString` was changed around 7.4 (4 years ago): https://github.com/haskell/bytestring/commit/8ea65

**Comment by matthewleon** [comment]
Hmm. I don't think we care about that test failure, do we? Had I defined these tests earlier, they would have failed on all earlier builds.

What's the right response to this? Change the test or decide we don't care about that version of GHC?

**Comment by creichert** [comment]
For this one instance, I think it's okay to try a bit of CPP. If this is a continual annoyance we can just drop the GHC version or handle it another way. If you have any objections I'm open to removing the CPP altogether. I intended to create a PR to test the build but ended up just pushing.

**Comment by creichert** [comment]
Another nice set of changes though, thanks!

**Comment by creichert** [comment]
We could use an allowed failure as well: https://github.com/creichert/bencode/blob/master/.travis.yml#L12

**Pull request merged**
